name: Run Backend and Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend-and-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          source venv/bin/activate
          export PYTHONPATH=.
          pytest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd simple-ts-ui
          npm install
          npm install @playwright/test --save-dev

      - name: Install Playwright Browsers
        run: |
          cd simple-ts-ui
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd simple-ts-ui
          npx playwright test